# This is used by the action https://github.com/tj-actions/changed-files
# NOTE: Filter order is irrelevant (unlike .gitignore).
# Positive filters are applied first, then negative filters.

# Always include CI changes to all filters so that all CI changes are always tested
ci-configs: &ci-configs
  - .github/**

# Mostly Koog's source code
koog-src:
  - *ci-configs
  - '**'
  - '!examples/**'
  - '!docs/**'
  - '!*.md'
  - '!.editorconfig'
  - '!.gitignore'

docs:
  - *ci-configs
  - 'docs/**'

simple-examples:
  - *ci-configs
  - 'examples/simple-examples/**'

simple-examples-java:
  - *ci-configs
  - 'examples/simple-examples-java/**'

code-agent:
  - *ci-configs
  - 'examples/code-agent/**'
