spring:
  application:
    name: spring-ai-kotlin
  ai:
    openai:
      chat:
        options:
          model: gpt-5-nano
          temperature: 1
      api-key: YOUR_OPENAI_API_KEY
      embedding:
        options:
          model: text-embedding-3-small
          dimensions: 768
    model:
      chat: openai
      embedding: openai
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 768
        index-type: hnsw
  docker:
    compose:
      file: docker-compose.yml
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5434/vectordb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect