package ai.koog.agents.core.feature.model.events

import ai.koog.agents.core.agent.execution.AgentExecutionInfo
import ai.koog.agents.core.feature.model.AIAgentError
import ai.koog.agents.utils.ModelInfo
import ai.koog.prompt.Prompt
import ai.koog.prompt.dsl.ModerationResult
import ai.koog.prompt.message.Message
import ai.koog.utils.time.KoogClock
import kotlinx.serialization.Serializable

/**
 * Represents an event indicating the start of a call to a Language Learning Model (LLM).
 *
 * This event captures the details of the LLM interaction at the point of invocation, including the
 * input prompt and any tools that will be used during the call. It extends the `DefinedFeatureEvent` class
 * and serves as a specific type of event in a feature-driven framework.
 *
 * @property eventId A unique identifier for the event or a group of events;
 * @property executionInfo Provides contextual information about the execution associated with this event.
 * @property runId A unique identifier associated with the specific run of the LLM call.
 * @property prompt The input prompt encapsulated as a [Prompt] object. This represents the structured set of
 *                  messages and configuration parameters sent to the LLM.
 * @property model The model information including provider, model, and context details.
 * @property tools The list of tools, represented by their string identifiers, being used within the scope
 *                 of the LLM call. These tools may extend or enhance the core functionality of the LLM.
 * @property timestamp The timestamp of the event, in milliseconds since the Unix epoch.
 */
@Serializable
public data class LLMCallStartingEvent(
    override val eventId: String,
    override val executionInfo: AgentExecutionInfo,
    val runId: String,
    val prompt: Prompt,
    val model: ModelInfo,
    val tools: List<String>,
    override val timestamp: Long = KoogClock.System.now().toEpochMilliseconds(),
) : DefinedFeatureEvent()

/**
 * Represents an event signaling the completion of an LLM (Large Language Model) call.
 *
 * This event encapsulates the responses provided by the LLM during its operation. It serves as a
 * record of the responses generated by the LLM, marking the end of a particular interaction cycle.
 * The event is used within the system to capture relevant output data and ensure proper tracking
 * and logging of LLM-related interactions.
 *
 * @property eventId A unique identifier for the event or a group of events;
 * @property executionInfo Provides contextual information about the execution associated with this event.
 * @property runId The unique identifier of the LLM run.
 * @property prompt The input prompt encapsulated as a [Prompt] object. This represents the structured set of
 *                  messages and configuration parameters sent to the LLM.
 * @property model The model information including provider, model, and context details.
 * @property response A list of responses generated by the LLM, represented as instances of [Message.Assistant].
 *                     Each response contains content, metadata, and additional context about the interaction.
 * @property moderationResponse The moderation response, if any, returned by the LLM.
 *                              This is typically used to capture and track content moderation results.
 * @property timestamp The timestamp of the event, in milliseconds since the Unix epoch.
 */
@Serializable
public data class LLMCallCompletedEvent(
    override val eventId: String,
    override val executionInfo: AgentExecutionInfo,
    val runId: String,
    val prompt: Prompt,
    val model: ModelInfo,
    val response: Message.Assistant?,
    val moderationResponse: ModerationResult? = null,
    override val timestamp: Long = KoogClock.System.now().toEpochMilliseconds(),
) : DefinedFeatureEvent()

/**
 * Represents an event that occurs when a call to a large language model (LLM) fails. This event captures
 * relevant details about the failed call, such as the prompt, model information, tools used, and the
 * associated error.
 *
 * @property eventId A unique identifier for the event.
 * @property executionInfo Execution context information, including the part name and any parent executions.
 * @property runId A unique identifier for the specific run of the LLM call that failed.
 * @property prompt The prompt data associated with the LLM call.
 * @property model Information about the model used for the LLM call.
 * @property tools A list of tools (if any) involved in the execution that led to the failure.
 * @property error The error information providing details about why the call failed.
 * @property timestamp The time at which the event was recorded, represented as milliseconds since epoch.
 */
@Serializable
public data class LLMCallFailedEvent(
    override val eventId: String,
    override val executionInfo: AgentExecutionInfo,
    val runId: String,
    val prompt: Prompt,
    val model: ModelInfo,
    val tools: List<String>,
    val error: AIAgentError,
    override val timestamp: Long = KoogClock.System.now().toEpochMilliseconds(),
) : DefinedFeatureEvent()
