package ai.koog.agents.core.feature.model.events

import ai.koog.agents.core.agent.execution.AgentExecutionInfo
import ai.koog.agents.core.feature.model.AIAgentError
import ai.koog.serialization.JSONElement
import ai.koog.utils.time.KoogClock
import kotlinx.serialization.Serializable

/**
 * Represents an event triggered when the execution of a specific AI agent node starts.
 *
 * This event captures the initial execution context of an AI agent's processing node.
 * It provides information about the node's name, the input being processed,
 * and a unique identifier for the event.
 *
 * Events of this kind are part of the feature event system and are primarily
 * used for tracking and monitoring purposes, particularly in scenarios where
 * understanding the flow of agent execution is essential.
 *
 * @property eventId A unique identifier for the event or a group of events;
 * @property executionInfo Provides contextual information about the execution associated with this event.
 * @property runId A unique identifier associated with the specific run of the AI agent;
 * @property nodeName The name of the node whose execution is starting;
 * @property input The input data provided to the node and serialized into JSON element;
 * @property timestamp The timestamp of the event, in milliseconds since the Unix epoch.
 */
@Serializable
public data class NodeExecutionStartingEvent(
    override val eventId: String,
    override val executionInfo: AgentExecutionInfo,
    val runId: String,
    val nodeName: String,
    val input: JSONElement?,
    override val timestamp: Long = KoogClock.System.now().toEpochMilliseconds(),
) : DefinedFeatureEvent()

/**
 * Represents an event indicating the completion of a node's execution within an AI agent.
 *
 * This event is triggered when a specific processing node, identified by its name,
 * concludes its execution. It encapsulates details about the node's name,
 * the input it operated on, and the output it produced.
 *
 * @property eventId A unique identifier for the event or a group of events;
 * @property executionInfo Provides contextual information about the execution associated with this event.
 * @property nodeName The name of the node that finished execution;
 * @property input The input data provided to the node;
 * @property output The output generated by the node;
 * @property timestamp The timestamp of the event, in milliseconds since the Unix epoch.
 */
@Serializable
public data class NodeExecutionCompletedEvent(
    override val eventId: String,
    override val executionInfo: AgentExecutionInfo,
    val runId: String,
    val nodeName: String,
    val input: JSONElement?,
    val output: JSONElement?,
    override val timestamp: Long = KoogClock.System.now().toEpochMilliseconds(),
) : DefinedFeatureEvent()

/**
 * Represents an event that signifies the occurrence of an error during the execution of a specific node
 * within an AI agent's process.
 *
 * @property eventId A unique identifier for the event or a group of events;
 * @property executionInfo Provides contextual information about the execution associated with this event.
 * @property runId A unique identifier associated with the specific run of the AI agent;
 * @property nodeName The name of the node where the error occurred;
 * @property input The input data provided to the node;
 * @property error An instance of `AIAgentError` containing the error details, such as a message, stack trace, and optional cause;
 * @property timestamp The timestamp of the event, in milliseconds since the Unix epoch.
 */
@Serializable
public data class NodeExecutionFailedEvent(
    override val eventId: String,
    override val executionInfo: AgentExecutionInfo,
    val runId: String,
    val nodeName: String,
    val input: JSONElement?,
    val error: AIAgentError,
    override val timestamp: Long = KoogClock.System.now().toEpochMilliseconds(),
) : DefinedFeatureEvent()
