package ai.koog.agents.core.feature.model.events

import ai.koog.agents.core.agent.execution.AgentExecutionInfo
import ai.koog.agents.core.feature.model.AIAgentError
import ai.koog.serialization.JSONElement
import ai.koog.serialization.JSONPrimitive
import ai.koog.utils.time.KoogClock
import kotlinx.serialization.Serializable

/**
 * Represents an event triggered when the execution of a specific AI agent node starts.
 *
 * This event captures the initial execution context of an AI agent's processing node.
 * It provides information about the node's name, the input being processed,
 * and a unique identifier for the event.
 *
 * Events of this kind are part of the feature event system and are primarily
 * used for tracking and monitoring purposes, particularly in scenarios where
 * understanding the flow of agent execution is essential.
 *
 * @property eventId A unique identifier for the event or a group of events;
 * @property executionInfo Provides contextual information about the execution associated with this event.
 * @property runId A unique identifier associated with the specific run of the AI agent;
 * @property nodeName The name of the node whose execution is starting;
 * @property input The input data provided to the node and serialized into JSON element;
 * @property timestamp The timestamp of the event, in milliseconds since the Unix epoch.
 */
@Serializable
public data class NodeExecutionStartingEvent(
    override val eventId: String,
    override val executionInfo: AgentExecutionInfo,
    val runId: String,
    val nodeName: String,
    val input: JSONElement?,
    override val timestamp: Long = KoogClock.System.now().toEpochMilliseconds(),
) : DefinedFeatureEvent() {

    /**
     * Creates an instance of [NodeExecutionStartingEvent].
     *
     * This constructor is deprecated and should be replaced with the constructor
     * that accepts [executionInfo] parameter, and an input parameter of type [JSONElement].
     */
    @Deprecated(
        message = "Use constructor with executionInfo parameter, and input parameter of type [JSONElement]",
        replaceWith = ReplaceWith("NodeExecutionStartingEvent(executionInfo, runId, nodeName, input, timestamp)")
    )
    public constructor(
        runId: String,
        nodeName: String,
        input: String,
        timestamp: Long = KoogClock.System.now().toEpochMilliseconds()
    ) : this(
        eventId = NodeExecutionStartingEvent::class.simpleName.toString(),
        executionInfo = AgentExecutionInfo(
            parent = null,
            partName = NodeExecutionStartingEvent::class.simpleName.toString(),
        ),
        runId = runId,
        nodeName = nodeName,
        input = JSONPrimitive(input),
        timestamp = timestamp
    )
}

/**
 * Represents an event indicating the completion of a node's execution within an AI agent.
 *
 * This event is triggered when a specific processing node, identified by its name,
 * concludes its execution. It encapsulates details about the node's name,
 * the input it operated on, and the output it produced.
 *
 * @property eventId A unique identifier for the event or a group of events;
 * @property executionInfo Provides contextual information about the execution associated with this event.
 * @property nodeName The name of the node that finished execution;
 * @property input The input data provided to the node;
 * @property output The output generated by the node;
 * @property timestamp The timestamp of the event, in milliseconds since the Unix epoch.
 */
@Serializable
public data class NodeExecutionCompletedEvent(
    override val eventId: String,
    override val executionInfo: AgentExecutionInfo,
    val runId: String,
    val nodeName: String,
    val input: JSONElement?,
    val output: JSONElement?,
    override val timestamp: Long = KoogClock.System.now().toEpochMilliseconds(),
) : DefinedFeatureEvent() {

    /**
     * Creates an instance of [NodeExecutionCompletedEvent].
     *
     * This constructor is deprecated and should be replaced with the constructor
     * that accepts [executionInfo] parameter, and [input] and [output] parameters of type [JSONElement].
     */
    @Deprecated(
        message = "Use constructor with executionInfo parameter, and input and output parameters of type [JSONElement]",
        replaceWith = ReplaceWith("NodeExecutionCompletedEvent(executionInfo, runId, nodeName, input, output, timestamp)")
    )
    public constructor(
        runId: String,
        nodeName: String,
        input: String,
        output: String,
        timestamp: Long = KoogClock.System.now().toEpochMilliseconds()
    ) : this(
        eventId = NodeExecutionCompletedEvent::class.simpleName.toString(),
        executionInfo = AgentExecutionInfo(
            parent = null,
            partName = NodeExecutionCompletedEvent::class.simpleName.toString(),
        ),
        runId = runId,
        nodeName = nodeName,
        input = JSONPrimitive(input),
        output = JSONPrimitive(output),
        timestamp = timestamp
    )
}

/**
 * Represents an event that signifies the occurrence of an error during the execution of a specific node
 * within an AI agent's process.
 *
 * @property eventId A unique identifier for the event or a group of events;
 * @property executionInfo Provides contextual information about the execution associated with this event.
 * @property runId A unique identifier associated with the specific run of the AI agent;
 * @property nodeName The name of the node where the error occurred;
 * @property input The input data provided to the node;
 * @property error An instance of `AIAgentError` containing the error details, such as a message, stack trace, and optional cause;
 * @property timestamp The timestamp of the event, in milliseconds since the Unix epoch.
 */
@Serializable
public data class NodeExecutionFailedEvent(
    override val eventId: String,
    override val executionInfo: AgentExecutionInfo,
    val runId: String,
    val nodeName: String,
    val input: JSONElement?,
    val error: AIAgentError,
    override val timestamp: Long = KoogClock.System.now().toEpochMilliseconds(),
) : DefinedFeatureEvent() {

    /**
     * Creates an instance of [NodeExecutionFailedEvent].
     *
     * This constructor is deprecated and should be replaced with the constructor
     * that accepts [executionInfo] parameter, and an input parameter of type [JSONElement].
     */
    @Deprecated(
        message = "Use constructor with executionInfo parameter, and input parameter of type [JSONElement]",
        replaceWith = ReplaceWith("NodeExecutionFailedEvent(executionInfo, runId, nodeName, input, error, timestamp)")
    )
    public constructor(
        runId: String,
        nodeName: String,
        error: AIAgentError,
        timestamp: Long = KoogClock.System.now().toEpochMilliseconds()
    ) : this(
        eventId = NodeExecutionFailedEvent::class.simpleName.toString(),
        executionInfo = AgentExecutionInfo(
            parent = null,
            partName = NodeExecutionFailedEvent::class.simpleName.toString(),
        ),
        runId = runId,
        nodeName = nodeName,
        input = null,
        error = error,
        timestamp = timestamp
    )
}

//region Deprecated

@Deprecated(
    message = "Use NodeExecutionStartingEvent instead",
    replaceWith = ReplaceWith("NodeExecutionStartingEvent")
)
public typealias AIAgentNodeExecutionStartEvent = NodeExecutionStartingEvent

@Deprecated(
    message = "Use NodeExecutionCompletedEvent instead",
    replaceWith = ReplaceWith("NodeExecutionCompletedEvent")
)
public typealias AIAgentNodeExecutionEndEvent = NodeExecutionCompletedEvent

@Deprecated(
    message = "Use NodeExecutionFailedEvent instead",
    replaceWith = ReplaceWith("NodeExecutionFailedEvent")
)
public typealias AIAgentNodeExecutionErrorEvent = NodeExecutionFailedEvent

//endregion Deprecated
