package ai.koog.agents.core.feature.model.events

import ai.koog.agents.core.agent.execution.AgentExecutionInfo
import ai.koog.agents.core.feature.model.AIAgentError
import ai.koog.serialization.JSONElement
import ai.koog.utils.time.KoogClock
import kotlinx.serialization.Serializable

/**
 * Represents an event triggered when the execution of a specific subgraph starts.
 *
 * This event captures the initiation of a subgraph execution, including details
 * such as the unique run identifier, the name of the subgraph, and the input data
 * provided to the subgraph.
 *
 * @property eventId A unique identifier for the event or a group of events;
 * @property executionInfo Provides contextual information about the execution associated with this event.
 * @property runId Unique identifier for the subgraph run;
 * @property subgraphName The name of the subgraph being executed;
 * @property input The input data provided to the subgraph;
 * @property timestamp The timestamp of the event, in milliseconds since the Unix epoch.
 */
@Serializable
public data class SubgraphExecutionStartingEvent(
    override val eventId: String,
    override val executionInfo: AgentExecutionInfo,
    val runId: String,
    val subgraphName: String,
    val input: JSONElement?,
    override val timestamp: Long = KoogClock.System.now().toEpochMilliseconds(),
) : DefinedFeatureEvent()

/**
 * Represents an event triggered when the execution of a specific subgraph completes.
 *
 * @property eventId A unique identifier for the event or a group of events;
 * @property executionInfo Provides contextual information about the execution associated with this event.
 * @property runId Unique identifier for the subgraph run;
 * @property subgraphName The name of the subgraph being executed;
 * @property input The input data provided to the subgraph;
 * @property output The output data generated by the subgraph;
 * @property timestamp The timestamp of the event, in milliseconds since the Unix epoch.
 */
@Serializable
public data class SubgraphExecutionCompletedEvent(
    override val eventId: String,
    override val executionInfo: AgentExecutionInfo,
    val runId: String,
    val subgraphName: String,
    val input: JSONElement?,
    val output: JSONElement?,
    override val timestamp: Long = KoogClock.System.now().toEpochMilliseconds(),
) : DefinedFeatureEvent()

/**
 * Represents an event triggered when the execution of a specific subgraph fails.
 *
 * @property eventId A unique identifier for the event or a group of events;
 * @property executionInfo Provides contextual information about the execution associated with this event.
 * @property runId Unique identifier for the subgraph run;
 * @property subgraphName The name of the subgraph being executed;
 * @property input The input data provided to the subgraph;
 * @property error The error that occurred during the subgraph execution;
 * @property timestamp The timestamp of the event, in milliseconds since the Unix epoch.
 */
@Serializable
public data class SubgraphExecutionFailedEvent(
    override val eventId: String,
    override val executionInfo: AgentExecutionInfo,
    val runId: String,
    val subgraphName: String,
    val input: JSONElement?,
    val error: AIAgentError,
    override val timestamp: Long = KoogClock.System.now().toEpochMilliseconds(),
) : DefinedFeatureEvent()
