@file:Suppress("EXPECT_ACTUAL_CLASSIFIERS_ARE_IN_BETA_WARNING")

package ai.koog.agents.core.agent.config

import ai.koog.prompt.dsl.Prompt
import ai.koog.prompt.executor.clients.openai.OpenAIModels
import ai.koog.prompt.llm.LLModel
import ai.koog.prompt.processor.ResponseProcessor
import ai.koog.serialization.JSONSerializer
import ai.koog.serialization.kotlinx.KotlinxSerializer
import kotlin.jvm.JvmName

/**
 * Configuration class for an AI agent that specifies the prompt, execution parameters, and behavior.
 *
 * This class is responsible for defining the various settings and components required
 * for an AI agent to operate. It includes the prompt configuration, iteration limits,
 * and strategies for handling missing tools during execution.
 *
 * @param prompt The initial prompt configuration for the agent, encapsulating messages, model, and parameters.
 * @param model The model to use for the agent's prompt execution
 * @param maxAgentIterations The maximum number of iterations allowed for an agent during its execution to prevent infinite loops.
 * @param missingToolsConversionStrategy Strategy used to determine how tool calls,
 *        present in the prompt but lacking definitions, are handled during agent execution.
 *        This property provides a mechanism to convert or format missing tool calls and result messages when they occur,
 *        typically due to differences in tool sets between steps or subgraphs while the same history is reused.
 *        This ensures the prompt remains consistent and readable for the model, even with undefined tools.
 * @param responseProcessor Optional processor for the agent's responses. If specified, will modify the responses from the llm.
 * @param serializer Optional serializer to (de)serialize tool arguments and results. Defaults to [KotlinxSerializer]
 */
public expect class AIAgentConfig(
    prompt: Prompt,
    model: LLModel,
    maxAgentIterations: Int,
    missingToolsConversionStrategy: MissingToolsConversionStrategy =
        MissingToolsConversionStrategy.Missing(ToolCallDescriber.JSON),
    responseProcessor: ResponseProcessor? = null,
    serializer: JSONSerializer = KotlinxSerializer(),
) : AIAgentConfigBase {

    /**
     * The prompt configuration used in the AI agent settings.
     *
     * This property represents the current prompt*/
    @get:JvmName("prompt")
    public override val prompt: Prompt

    /**
     * Specifies the Large Language Model (LLM) configuration to be used by the AI agent.
     *
     * This property defines the specific language model leveraged by the AI agent,
     * including its provider, identifier, supported capabilities, context length, and
     * maximum output tokens. It determines how the agent processes inputs, generates
     * outputs, and interacts with other components or tools as part of its functionality.
     */
    @get:JvmName("model")
    public override val model: LLModel

    /**
     * Specifies the maximum number of iterations an AI agent is allowed to execute.
     *
     * This property defines the upper limit on the number of cycles the AI agent can perform
     * during its*/
    @get:JvmName("maxAgentIterations")
    public val maxAgentIterations: Int

    /**
     * The response processor used for handling and modifying responses
     * generated by LLM.
     *
     * This optional property allows customization of response processing logic.
     * A [ResponseProcessor] can perform tasks such as filtering, enriching, or otherwise
     * transforming generated responses before they are returned or utilized.
     *
     * Tipical usecase for [ResponseProcessor] is to extract tool calls from plasin textual responses
     * (sometimes small models return tool calls as part of the textual assistant message instead of using tools API).
     */
    @get:JvmName("responseProcessor")
    public val responseProcessor: ResponseProcessor?

    /**
     * Defines the strategy for converting tool calls in the prompt when some tool definitions
     * are missing in the request. This is particularly relevant when managing multi-stage processing
     * or subgraphs where tools used in different*/
    @get:JvmName("missingToolsConversionStrategy")
    public val missingToolsConversionStrategy: MissingToolsConversionStrategy

    /**
     * Serializer to (de)serialize tool arguments and results.
     */
    @get:JvmName("serializer")
    public val serializer: JSONSerializer

    /**
     * Companion object for providing utility methods related to [AIAgentConfig].
     */
    public companion object {

        /**
         * Creates an AI agent configuration with a specified system prompt.
         *
         * This function initializes an instance of [AIAgentConfig] using the provided system-level prompt
         * and other optional parameters, such as the language model, configuration ID, and maximum agent iterations.
         *
         * @param prompt The content of the system prompts to define the context and instructions for the AI agent.
         * @param llm The Large Language Model (LLM) to be used for the AI agent. Defaults to OpenAIModels.Chat.GPT4o.
         * @param id The identifier for the agent configuration. Defaults to "koog-agents".
         * @param maxAgentIterations The maximum number of iterations the agent can perform to avoid infinite loops. Defaults to 3.
         * @return An instance of [AIAgentConfig] representing the AI agent configuration with the specified parameters.
         */
        public fun withSystemPrompt(
            prompt: String,
            llm: LLModel = OpenAIModels.Chat.GPT4o,
            id: String = "koog-agents",
            maxAgentIterations: Int = 3,
        ): AIAgentConfig
    }

    /**
     * Creates a copy of this AI agent configuration with the specified modifications.
     *
     * @param prompt The prompt to use for the AI agent. Defaults to the existing prompt.
     * @param model The LLM model to use for the AI agent. Defaults to the existing model.
     * @param maxAgentIterations The maximum number of iterations allowed for the AI agent. Defaults to the existing value.
     * @param missingToolsConversionStrategy The strategy for handling missing tools during the AI agent's execution. Defaults to the existing strategy.
     * @param responseProcessor The processor for handling responses from the LLM. Defaults to the existing processor.
     * @param serializer The serializer for handling tool arguments and results. Defaults to the existing serializer.
     * @return A new instance of [AIAgentConfig] with the specified modifications.
     */
    internal fun copy(
        prompt: Prompt = this.prompt,
        model: LLModel = this.model,
        maxAgentIterations: Int = this.maxAgentIterations,
        missingToolsConversionStrategy: MissingToolsConversionStrategy = this.missingToolsConversionStrategy,
        responseProcessor: ResponseProcessor? = this.responseProcessor,
        serializer: JSONSerializer = this.serializer
    ): AIAgentConfig
}
