@file:Suppress("EXPECT_ACTUAL_CLASSIFIERS_ARE_IN_BETA_WARNING")
@file:OptIn(InternalPromptAPI::class)

package ai.koog.prompt.executor.clients

import ai.koog.agents.annotations.JavaAPI
import ai.koog.agents.core.tools.ToolDescriptor
import ai.koog.prompt.annotations.InternalPromptAPI
import ai.koog.prompt.dsl.ModerationResult
import ai.koog.prompt.dsl.Prompt
import ai.koog.prompt.llm.LLModel
import ai.koog.prompt.message.LLMChoice
import ai.koog.prompt.message.Message
import ai.koog.prompt.streaming.StreamFrame
import ai.koog.utils.annotations.InternalKoogUtils
import ai.koog.utils.concurrency.runBlockingReentrant
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.asCoroutineDispatcher
import kotlinx.coroutines.jdk9.asPublisher
import java.util.concurrent.ExecutorService
import java.util.concurrent.Flow

/**
 * Common interface for direct communication with LLM providers.
 * This interface defines methods for executing prompts and streaming responses.
 *
 * Implements [AutoCloseable] as LLM clients typically work with IO resources. Always close it when finished.
 */
public actual abstract class LLMClient actual constructor() : LLMClientAPI, LLMEmbeddingProvider() {
    /**
     * Executes a prompt and returns a list of response messages.
     *
     * @param prompt The prompt to execute
     * @param model The LLM model to use
     * @param tools Optional list of tools that can be used by the LLM
     * @param executorService An optional [ExecutorService] that can be provided to control the execution context.
     * @return List of response messages
     */
    @OptIn(InternalKoogUtils::class)
    @JavaAPI
    @JvmOverloads
    public fun execute(
        prompt: Prompt,
        model: LLModel,
        tools: List<ToolDescriptor> = emptyList(),
        executorService: ExecutorService? = null
    ): List<Message.Response> = runBlockingReentrant(
        executorService?.asCoroutineDispatcher() ?: Dispatchers.IO
    ) {
        execute(prompt, model, tools)
    }

    /**
     * Executes a prompt and returns a list of LLM choices.
     *
     * @param prompt The prompt to execute
     * @param tools Optional list of tools that can be used by the LLM
     * @param model The LLM model to use
     * @param executorService An optional [ExecutorService] that can be provided to control the execution context.
     *  @return List of LLM choices
     */
    @OptIn(InternalKoogUtils::class)
    @JavaAPI
    @JvmOverloads
    public fun executeMultipleChoices(
        prompt: Prompt,
        model: LLModel,
        tools: List<ToolDescriptor> = emptyList(),
        executorService: ExecutorService? = null
    ): List<LLMChoice> = runBlockingReentrant(
        executorService?.asCoroutineDispatcher() ?: Dispatchers.IO
    ) {
        executeMultipleChoices(prompt, model, tools)
    }

    /**
     * Executes a given prompt using the specified language model (LLM) and tools,
     * providing the results as a synchronous stream of [StreamFrame] objects.
     *
     * @param prompt The [Prompt] object containing the input messages and parameters for the execution.
     * @param model The [LLModel] instance specifying the language model to be used.
     * @param tools An optional list of [ToolDescriptor] objects defining the tools available during execution. Defaults to an empty list.
     * @return A [Flow.Publisher] that emits [StreamFrame] objects representing streamed responses generated by the LLM.
     */
    @JavaAPI
    @JvmOverloads
    public fun executeStreamingWithPublisher(
        prompt: Prompt,
        model: LLModel,
        tools: List<ToolDescriptor> = emptyList(),
    ): Flow.Publisher<StreamFrame> = executeStreaming(prompt, model, tools).asPublisher()

    /**
     * Analyzes the provided prompt for violations of content policies or other moderation criteria.
     *
     * @param prompt The input prompt to be analyzed for moderation.
     * @param model The language model to be used for conducting the moderation analysis.
     * @param executorService An optional [ExecutorService] that can be provided to control the execution context.
     * @return The result of the moderation analysis, encapsulated in a ModerationResult object.
     */
    @OptIn(InternalKoogUtils::class)
    @JavaAPI
    @JvmOverloads
    public fun moderate(
        prompt: Prompt,
        model: LLModel,
        executorService: ExecutorService? = null
    ): ModerationResult = runBlockingReentrant(
        executorService?.asCoroutineDispatcher() ?: Dispatchers.IO
    ) {
        moderate(prompt, model)
    }

    /**
     * Retrieves a list of ids of available Large Language Models (LLMs) supported by the client.
     * @param executorService An optional [ExecutorService] that can be provided to control the execution context.
     * @return A list of model ids instances representing the available LLMs.
     */
    @OptIn(InternalKoogUtils::class)
    @JavaAPI
    @JvmOverloads
    public fun models(executorService: ExecutorService? = null): List<LLModel> = runBlockingReentrant(
        executorService?.asCoroutineDispatcher() ?: Dispatchers.IO
    ) {
        models()
    }
}
